[tool.poetry]
name = "python-driver-docs"
version = "0.1.0"
description = "ScyllaDB Python Driver Docs"
authors = ["Python Driver Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
geomet = "0.1.2"
six = "1.15.0"
futures = "2.2.0"
eventlet = "0.25.2"
gevent = "20.12.1"
scales = "1.0.9"
[tool.poetry.dev-dependencies]
sphinx-autobuild = "0.7.1"
Sphinx = "2.4.4"
jinja2 = "2.8.1"
gremlinpython = "3.4.7"
recommonmark = "0.5.0"
sphinx-scylladb-theme = "~0.1.10"
sphinx-multiversion-scylla = "~0.2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
