name: Build and upload to PyPi

on:
  push:
    branches:
      - master
      - 'branch-**'
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/lib-build-and-push.yml
    with:
      upload: ${{ endsWith(github.event.ref, 'scylla') }}
