name: Test wheels building

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - examples/**
      - scripts/**
      - .gitignore
      - '**/*.rst'
      - '**/*.md'
      - '*.ini'
      - LICENSE
      - .github/dependabot.yml
      - .github/pull_request_template.md
      - .github/workflows/docs-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-wheels-build:
    name: "Test wheels building"
    if: "!contains(github.event.pull_request.labels.*.name, 'disable-test-build')"
    uses: ./.github/workflows/lib-build.yml
