name: "Docs / Build PR"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
      - "cassandra/**"
      - "pyproject.toml"
      - "setup.py"
      - "CHANGELOG.rst"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
      - "cassandra/**"
      - "pyproject.toml"
      - "setup.py"
      - "CHANGELOG.rst"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: docs
          enable-cache: true

      - name: Build docs
        run: make -C docs test
