name: "Docs / Build PR"

on:
  pull_request:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.7
      - name: Setup Cassandra dependencies
        run: sudo apt-get install gcc python-dev libev4 libev-dev
      - name: Build driver
        run: python setup.py develop
      - name: Set up Poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Build docs
        run: make -C docs test
