name: "Docs / Publish"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    branches:
      - master
      - 'branch-**'
    paths:
      - "docs/**"
      - ".github/workflows/docs-pages.yml"
      - "cassandra/**"
      - "pyproject.toml"
      - "setup.py"
      - "CHANGELOG.rst"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: docs
          enable-cache: true

      - name: Build docs
        run: make -C docs multiversion

      - name: Build redirects
        run: make -C docs redirects

      - name: Deploy docs to GitHub Pages
        run: ./docs/_utils/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
