name: "Docs / Build PR"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
      - "cassandra/**"
      - "pyproject.toml"
      - "setup.py"
      - "CHANGELOG.rst"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
      - "cassandra/**"
      - "pyproject.toml"
      - "setup.py"
      - "CHANGELOG.rst"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Set up env
        run: make -C docs setupenv

      - name: Build docs
        run: make -C docs test
